require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SoundClipsController do

  # This should return the minimal set of attributes required to create a valid
  # SoundClip. As you add validations to SoundClip, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SoundClipsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all sound_clips as @sound_clips" do
      sound_clip = SoundClip.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sound_clips).should eq([sound_clip])
    end
  end

  describe "GET show" do
    it "assigns the requested sound_clip as @sound_clip" do
      sound_clip = SoundClip.create! valid_attributes
      get :show, {:id => sound_clip.to_param}, valid_session
      assigns(:sound_clip).should eq(sound_clip)
    end
  end

  describe "GET new" do
    it "assigns a new sound_clip as @sound_clip" do
      get :new, {}, valid_session
      assigns(:sound_clip).should be_a_new(SoundClip)
    end
  end

  describe "GET edit" do
    it "assigns the requested sound_clip as @sound_clip" do
      sound_clip = SoundClip.create! valid_attributes
      get :edit, {:id => sound_clip.to_param}, valid_session
      assigns(:sound_clip).should eq(sound_clip)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SoundClip" do
        expect {
          post :create, {:sound_clip => valid_attributes}, valid_session
        }.to change(SoundClip, :count).by(1)
      end

      it "assigns a newly created sound_clip as @sound_clip" do
        post :create, {:sound_clip => valid_attributes}, valid_session
        assigns(:sound_clip).should be_a(SoundClip)
        assigns(:sound_clip).should be_persisted
      end

      it "redirects to the created sound_clip" do
        post :create, {:sound_clip => valid_attributes}, valid_session
        response.should redirect_to(SoundClip.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sound_clip as @sound_clip" do
        # Trigger the behavior that occurs when invalid params are submitted
        SoundClip.any_instance.stub(:save).and_return(false)
        post :create, {:sound_clip => {}}, valid_session
        assigns(:sound_clip).should be_a_new(SoundClip)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SoundClip.any_instance.stub(:save).and_return(false)
        post :create, {:sound_clip => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sound_clip" do
        sound_clip = SoundClip.create! valid_attributes
        # Assuming there are no other sound_clips in the database, this
        # specifies that the SoundClip created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SoundClip.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => sound_clip.to_param, :sound_clip => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested sound_clip as @sound_clip" do
        sound_clip = SoundClip.create! valid_attributes
        put :update, {:id => sound_clip.to_param, :sound_clip => valid_attributes}, valid_session
        assigns(:sound_clip).should eq(sound_clip)
      end

      it "redirects to the sound_clip" do
        sound_clip = SoundClip.create! valid_attributes
        put :update, {:id => sound_clip.to_param, :sound_clip => valid_attributes}, valid_session
        response.should redirect_to(sound_clip)
      end
    end

    describe "with invalid params" do
      it "assigns the sound_clip as @sound_clip" do
        sound_clip = SoundClip.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SoundClip.any_instance.stub(:save).and_return(false)
        put :update, {:id => sound_clip.to_param, :sound_clip => {}}, valid_session
        assigns(:sound_clip).should eq(sound_clip)
      end

      it "re-renders the 'edit' template" do
        sound_clip = SoundClip.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SoundClip.any_instance.stub(:save).and_return(false)
        put :update, {:id => sound_clip.to_param, :sound_clip => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sound_clip" do
      sound_clip = SoundClip.create! valid_attributes
      expect {
        delete :destroy, {:id => sound_clip.to_param}, valid_session
      }.to change(SoundClip, :count).by(-1)
    end

    it "redirects to the sound_clips list" do
      sound_clip = SoundClip.create! valid_attributes
      delete :destroy, {:id => sound_clip.to_param}, valid_session
      response.should redirect_to(sound_clips_url)
    end
  end

end
